# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.3
_src_path: gh:algorandfoundation/algokit-python-template
author_email: iamosmannyildiz@gmail.com
author_name: osmannyildiz
contract_name: poll_manager
deployment_language: python
preset_name: starter
project_name: polls-dapp-contracts

